server:
   port: 9002
   
eureka:
    instance:
     instance-id: ${spring.application.name}:${random.value}


spring:
   application:
     name: Chilton-Bulletin-Service
     
   datasource:
    url: jdbc:mysql://localhost:8306/chiltonbulletin
    username: admin
    password: adminRocks
    driver-class-name: com.mysql.cj.jdbc.Driver
    
 
   cloud:
    compatibility-verifier:
      enabled: false
